# Generated by Django 6.0.3 on 2026-06-15 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('specialty', models.CharField(choices=[('cardiologist', 'Cardiologist'), ('dermatologist', 'Dermatologist'), ('neurologist', 'Neurologist')], max_length=100)),
                ('image', models.ImageField(upload_to='doctors/')),
                ('institution', models.CharField(max_length=100)),
                ('visits', models.IntegerField(default=0)),
                ('mail', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit', models.CharField(choices=[('cardiology', 'Cardiology'), ('dermatology', 'Dermatology'), ('neurology', 'Neurology')], max_length=20)),
                ('symptoms', models.TextField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('finished', 'Finished')], max_length=20)),
                ('time', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('assistants', models.ManyToManyField(blank=True, related_name='assistant_exam', to='hospital_app.doctor')),
                ('responsible_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_exam', to='hospital_app.doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='hospital_app.patient')),
            ],
        ),
    ]
