# Generated by Django 6.0.3 on 2026-06-15 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointment',
            new_name='AppointmentAssignment',
        ),
    ]
