# Generated by Django 6.0.3 on 2026-06-15 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0002_rename_appointment_appointmentassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='visits',
        ),
        migrations.AddField(
            model_name='appointmentassignment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital_app.doctor'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='completed_appointments',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='institution',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_type', models.CharField(choices=[('cardiology', 'Cardiology'), ('dermatology', 'Dermatology'), ('neurology', 'Neurology')], max_length=20)),
                ('symptoms', models.TextField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('finished', 'Finished')], max_length=20)),
                ('datetime', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='hospital_app.patient')),
                ('responsible_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_appointments', to='hospital_app.doctor')),
            ],
        ),
        migrations.AddField(
            model_name='appointmentassignment',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital_app.appointment'),
        ),
        migrations.AlterUniqueTogether(
            name='appointmentassignment',
            unique_together={('appointment', 'doctor')},
        ),
        migrations.RemoveField(
            model_name='appointmentassignment',
            name='assistants',
        ),
        migrations.RemoveField(
            model_name='appointmentassignment',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='appointmentassignment',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='appointmentassignment',
            name='responsible_doctor',
        ),
        migrations.RemoveField(
            model_name='appointmentassignment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='appointmentassignment',
            name='symptoms',
        ),
        migrations.RemoveField(
            model_name='appointmentassignment',
            name='time',
        ),
        migrations.RemoveField(
            model_name='appointmentassignment',
            name='visit',
        ),
    ]
