# Generated by Django 6.0.3 on 2026-06-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0003_remove_doctor_visits_appointmentassignment_doctor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='symptoms',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='notes',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='mail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='birthday',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='mail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_type',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='surname',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('finished', 'Finished')], default='scheduled', max_length=20),
        ),
    ]
