# Generated by Django 6.0.6 on 2026-06-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='description',
        ),
        migrations.RemoveField(
            model_name='band',
            name='place',
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
