# Generated by Django 6.0.3 on 2026-03-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplement',
            old_name='created_by',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='supplement',
            name='category',
        ),
        migrations.AlterField(
            model_name='company',
            name='company_type',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=10),
        ),
        migrations.AlterField(
            model_name='supplement',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
