# Generated by Django 6.0.5 on 2026-05-11 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('year_founded', models.IntegerField()),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
                ('location', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('area', models.FloatField()),
                ('rooms', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('build_year', models.IntegerField()),
                ('property_type', models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('land', 'Land'), ('commercial', 'Commercial'), ('studio', 'Studio'), ('villa', 'Villa'), ('office', 'Office')], max_length=20)),
                ('status', models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent'), ('sold', 'Sold'), ('rented', 'Rented')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.agency')),
            ],
        ),
    ]
