# Generated by Django 6.0.5 on 2026-05-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('HOUSE', 'House'), ('APARTMENT', 'Apartment'), ('LAND', 'Land'), ('COMMERCIAL', 'Commercial'), ('STUDIO', 'Studio'), ('VILLA', 'Villa'), ('OFFICE', 'Office')], max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('For Sale', 'Sale'), ('For Rent', 'Rent'), ('Sold', 'Sold'), ('Rented', 'Rented')], max_length=20),
        ),
    ]
