# Generated by Django 6.0.5 on 2026-05-11 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('founded_year', models.IntegerField()),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('poster', models.ImageField(upload_to='posters/')),
                ('imbd_code', models.FloatField()),
                ('year', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('genre', models.CharField(choices=[('ACTION', 'Action'), ('COMEDY', 'Comedy'), ('DRAMA', 'Drama'), ('SCIENCE_FICTION', 'Science Fiction'), ('HORROR', 'Horror'), ('MUSICAL', 'Musical'), ('DOCUMENTARY', 'Documentary')], max_length=100)),
                ('format', models.CharField(choices=[('DVD', 'DVD'), ('BLU-RAY', 'Blu-ray'), ('DIGITAL', 'Digital')], max_length=100)),
                ('rental_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('production_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.production')),
            ],
        ),
    ]
