# Generated by Django 6.0.6 on 2026-06-17 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_num', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duration', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('kinematski', 'Kinematski'), ('FPV', 'FPV'), ('industriski', 'Industriski')], max_length=50)),
                ('photo', models.ImageField(upload_to='photos')),
                ('status', models.CharField(choices=[('dostapen', 'Dostapen'), ('rezerviran', 'Rezerviran'), ('na_servis', 'Na servis')], max_length=50)),
                ('company', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('num_reservations', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PilotReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dronovi_ap.drone')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dronovi_ap.pilot')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('termin', models.CharField(choices=[('utro', 'Utro'), ('popladne', 'Popladne'), ('vecher', 'Vecher')], max_length=50)),
                ('status', models.CharField(choices=[('na_chekanje', 'Na chekanje'), ('aktivna', 'Aktivna'), ('zavrshena', 'Zavrshena')], max_length=50)),
                ('note', models.TextField()),
                ('code', models.CharField(max_length=100)),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dronovi_ap.drone')),
                ('main_pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dronovi_ap.pilot')),
            ],
            options={
                'unique_together': {('drone', 'date', 'termin')},
            },
        ),
    ]
